# Generated by Django 4.2.2 on 2023-08-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital_user_Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Registration_number", models.CharField(max_length=16)),
                ("Hospital_Email", models.EmailField(max_length=254)),
                ("Gender", models.CharField(max_length=12)),
                ("Password", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Patient_Medical_Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Symptoms", models.TextField(max_length=1200)),
                ("Tests", models.TextField(max_length=550)),
                ("Results", models.TextField(max_length=550)),
                ("Diagnosis", models.CharField(max_length=100)),
                ("Prescription", models.CharField(max_length=300)),
                ("Recomendations", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Patient_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=12, null=True)),
                ("Second_name", models.CharField(max_length=12, null=True)),
                ("Other_name", models.CharField(max_length=12, null=True)),
                ("Identity_No", models.IntegerField(null=True)),
                ("Date_of_birth", models.DateField(blank=True, null=True)),
                ("Gender", models.CharField(max_length=16, null=True)),
                ("Residence", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "Hospital",
                    models.CharField(default="", max_length=50, null=True, unique=True),
                ),
                ("Username", models.CharField(max_length=12, null=True)),
                ("Password", models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
