# Generated by Django 4.2.2 on 2023-08-15 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patient_registration",
            new_name="HospitalPatient_registration",
        ),
    ]
