# Generated by Django 4.2.2 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0003_medicalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_medical_record",
            name="Image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
