# Generated by Django 4.2.2 on 2023-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0004_patient_medical_record_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital_user_registration",
            name="username",
            field=models.TextField(default="", max_length=16),
        ),
    ]
