# Generated by Django 4.2.2 on 2023-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0005_hospital_user_registration_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital_user_registration",
            name="username",
            field=models.CharField(default="", max_length=16),
        ),
    ]
