# Generated by Django 4.2.2 on 2023-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("hospital", "Hospital"), ("patient", "Patient")],
                default="patient",
                max_length=20,
            ),
        ),
    ]
