# Generated by Django 4.2.2 on 2023-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("hospital", "Hospital"), ("patient", "Patient")],
                max_length=20,
            ),
        ),
    ]
