# Generated by Django 4.2.2 on 2023-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_hospital_name_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="Hospital",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
