# Generated by Django 4.2.2 on 2023-08-30 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_rename_hospital_doctor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctordata",
            old_name="hospital",
            new_name="doctor",
        ),
    ]
