# Generated by Django 4.2.2 on 2023-09-27 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_password_patient_password_patient_identity"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
