# Generated by Django 4.2.2 on 2023-10-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_customuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="hospitals",
            field=models.ManyToManyField(related_name="patients", to="user.hospital"),
        ),
    ]
