# Generated by Django 4.2.2 on 2023-10-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_hospital_customuser_hospitals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="identity",
            field=models.CharField(
                default="",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
