# Generated by Django 4.2.2 on 2024-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_patient_identity_alter_patient_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="reg_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
