# Generated by Django 4.2.2 on 2025-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_doctor_reg_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
