# Generated by Django 4.2.2 on 2025-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_doctor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reg_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
