# Generated by Django 4.2.2 on 2023-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
                ("Username", models.CharField(max_length=100)),
                ("Password", models.CharField(default="", max_length=15)),
                (
                    "category",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
                ("category", models.TextField()),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Patient_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=12, null=True)),
                ("Second_name", models.CharField(max_length=12, null=True)),
                ("Other_name", models.CharField(max_length=12, null=True)),
                ("Identity_No", models.PositiveIntegerField(null=True)),
                ("Date_of_birth", models.DateField(blank=True, null=True)),
                ("Gender", models.CharField(max_length=16, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "Username",
                    models.CharField(default="", max_length=50, null=True, unique=True),
                ),
                ("Residence", models.CharField(max_length=12, null=True)),
                ("Password", models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatientUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Identity_No", models.PositiveIntegerField(null=True)),
                ("email", models.CharField(max_length=50)),
                ("hospital", models.TextField()),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
