# Generated by Django 4.2.2 on 2023-07-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0002_rename_email_hospitalupload_patient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient_registration",
            name="Residence",
        ),
        migrations.AddField(
            model_name="patient_registration",
            name="Hospital",
            field=models.CharField(default="", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="patient_registration",
            name="Username",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
