# Generated by Django 4.2.2 on 2023-07-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0005_hospitalupload_user_alter_hospitalupload_file"),
    ]

    operations = [
       
    ]
