# Generated by Django 4.2.2 on 2023-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0009_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("reg_number", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("Username", models.CharField(max_length=100)),
                ("Password", models.CharField(default="", max_length=15)),
                (
                    "category",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Hospital_registration",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("patient", "Patient")], max_length=10
            ),
        ),
    ]
